version: 2.1

jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run: |
            postman collection run "postman/collections/Accounts_29ebd449-460c-4bd5-8655-e553d9ab242f.json" -e "24113219-ab498e03-4831-42c8-9d32-a52294b7d2f3" --integration-id "131578-${CIRCLE_WORKFLOW_JOB_ID}"
            postman collection run "postman/collections/Accounts Integration Test_21d91a5b-45c8-4454-b2d3-913df2a3b879.json" -e "24113219-ab498e03-4831-42c8-9d32-a52294b7d2f3" --integration-id "131578-${CIRCLE_WORKFLOW_JOB_ID}"
      - run:
          name: Lint your API using Postman CLI
          command: postman api lint b70a5649-1775-40cf-876d-298af798cd54 --integration-id 131578

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
