version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout

      - newman/newman-run:
          collection: https://api.getpostman.com/collections/15405603-e9a1bfc0-f373-42dd-9e9c-f83930f5a0ea?apikey=$POSTMAN_API_KEY
          environment: https://api.getpostman.com/environments/15405603-1cd1937d-65f1-48ac-a5ca-2512ce7c4b32?apikey=$POSTMAN_API_KEY


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  newman-workflow:
    jobs:
      - newman-collection-run