version: 2.1

jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run: |
            postman collection run "16727226-7d488b0b-e728-4c61-888a-8d0cb70c842f" -e "15405603-1cd1937d-65f1-48ac-a5ca-2512ce7c4b32" --integration-id "104175-${CIRCLE_WORKFLOW_JOB_ID}"
      - run:
          name: Lint your API using Postman CLI
          command: postman api lint --integration-id 104175

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests